version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "qa-eks-node-drainer"
s3_bucket = "qa-autoscaling"
s3_prefix = "qa-autoscaling-node-drainer-sam"
capabilities = "CAPABILITY_NAMED_IAM"
region = "ap-northeast-1"
confirm_changeset = false
parameter_overrides = "AutoScalingGroup=\"qa-nss-tokyo-starpay-cloud-eks19-dev\" EksCluster=\"qa-nss-tokyo-starpay-cloud-eks19\""